[package]
name = "planner"
version = "0.1.0"
authors = ["BjÃ¸rnar Luteberget <luteberget@gmail.com>"]
edition = "2018"

[dependencies]
rolling = { path = "../rolling" }
smallvec = "*"
minisat = "0.4"
log = "0.4"

[dev-dependencies]
maplit = "1.0"
