[package]
name = "livehtml"
version = "0.1.0"
authors = ["Bj√∏rnar Luteberget <luteberget@gmail.com>"]

[dependencies]
webbrowser="*"
serde_json = "*"
ws = "*"
notify = "*"
milelang = { path = "../milelang" }
vis_rs = { path = "../vis-rs" }
rolling = { path = "../rolling" }
